Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path("",include("core.urls")),
    path("accounts/",include("userauth.urls")),
    path('accounts/', include('allauth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_ENABLED is True:
    urlpatterns += [path('admin/', admin.site.urls),]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

core/urls.py
from django.urls import path,include
from .views import index,StoreView,ProductView,VendorView,CategoryView,CartView,CheckoutView,OrderDetailView,PayMentCompletedView,WishListView
from .function import search,search_vendor,filter_product,check_product,add_to_cart,delete_from_cart,update_from_cart,order_create,add_review,delete_order,add_to_wishlist,remove_from_wishlist
urlpatterns = [
    path("",index,name="index"),

    path("store/",StoreView,name="store"),
    path("filter-product/",filter_product,name="filter-product"),

    path("product/<pid>/",ProductView,name="product-detail"),
    path("check-product/",check_product,name="check-product"),
    path("add-to-cart/",add_to_cart,name="add-to-cart"),
    path("add-review/",add_review,name="add-review"),

    path("shop/<vid>/",VendorView,name="vendor-detail"),
    path("category/<cid>",CategoryView,name="category-detail"),


    path("cart/",CartView,name="cart-detail"),
    path("<pid>/delete-from-cart/",delete_from_cart,name="delete"),
    path("update-from-cart/",update_from_cart,name="update"),

    path("search/",search,name="search"),
    path("searchVendor/",search_vendor,name="searchVendor"),

    path("checkout/",CheckoutView,name="checkout"),
    path("order/",order_create,name="order"),
    path("order-detail/<invoice>",OrderDetailView,name="order-detail"),
    path("delete-order/<invoice>",delete_order,name="delete-order"),
    path("paypal/",include("paypal.standard.ipn.urls")),
    path("payment-completed/",PayMentCompletedView,name="payment-completed"),

    path("wishlist",WishListView,name="wishlist"),
    path("add-to-wishlist/",add_to_wishlist,name="add-to-wishlist"),
    path("remove-from-wishlist/<pid>",remove_from_wishlist,name="remove-from-wishlist")
]

userauth/urls.py
from django.urls import path
from .views import register_view,login_view,logout_view,follow,profile_view,edit_profile,MessageView
from chat.views import index,chatPage
app_name = "userauth"
urlpatterns = [
    path("register/",register_view,name="register"),
    path("login/",login_view,name="login"),
    path("logout/",logout_view,name="logout"),
    path("follow/<vid>/",follow,name="follow"),
    path("",profile_view,name="profile"),
    path("profile/",edit_profile,name="profile-update"),
    path("inbox/",index,name="chat"),
    path("chat-user/<uid>/",chatPage,name="chat-page"),

]

chat/models.py
from django.db import models
from userauth.models import User
# Create your models here.
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Ecommerce.settings")

class ChatModel(models.Model):
    sender = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name="sender")
    receiver = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name="receiver")
    message = models.TextField(null=True, blank=True)
    thread_name = models.CharField(null=True, blank=True, max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.message

chat/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from .models import ChatModel
from userauth.models import User
# Create your views here.


def index(request):
   # users = User.objects.exclude(id=request.user.id)
    #users = User.objects.exclude(username=request.user.username)
    print(ChatModel.objects.filter(sender=request.user).all().values_list("receiver_id",flat=True))
    users = User.objects.filter(id__in=ChatModel.objects.filter(sender=request.user).all().values_list("receiver_id",flat=True))
    user_obj = User.objects.get(id=ChatModel.objects.filter(sender=request.user).all().values_list("receiver_id",flat=True).order_by("timestamp").first())
    print(user_obj)
    if request.user.id > user_obj.id:
        thread_name = f'chat_{request.user.id}-{user_obj.id}'
    else:
        thread_name = f'chat_{user_obj.id}-{request.user}'
    message_objs = ChatModel.objects.filter(sender__in=[request.user,user_obj],receiver__in=[request.user,user_obj])
    print(message_objs)
    return render(request, 'chat/base.html', context={'first_user': user_obj,'users': users, 'messages': message_objs})


def chatPage(request, uid):
    user_obj = User.objects.get(id=uid)
    users = User.objects.filter(id__in=ChatModel.objects.filter(sender=request.user).all().values_list("receiver_id",flat=True))
    if request.user.id > user_obj.id:
        thread_name = f'chat_{request.user.id}-{user_obj.id}'
    else:
        thread_name = f'chat_{user_obj.id}-{request.user.id}'
    message_objs = ChatModel.objects.filter(thread_name=thread_name)
    return render(request, 'chat/chat.html', context={'user': user_obj, 'users': users, 'messages': message_objs})

templates/chat.html
{% extends "index.html" %}
{%load static%}
{%block body%}
<style>
    body{
        background-color: #f4f7f6;
        margin-top:20px;
    }
    .card {
        background: #fff;
        transition: .5s;
        border: 0;
        margin-bottom: 30px;
        border-radius: .55rem;
        position: relative;
        width: 100%;
        box-shadow: 0 1px 2px 0 rgb(0 0 0 / 10%);
    }
    .chat-app .people-list {
        width: 280px;
        position: absolute;
        left: 0;
        top: 0;
        padding: 20px;
        z-index: 7
    }
    
    .chat-app .chat {
        margin-left: 280px;
        border-left: 1px solid #eaeaea
    }
    
    .people-list {
        -moz-transition: .5s;
        -o-transition: .5s;
        -webkit-transition: .5s;
        transition: .5s
    }
    
    .people-list .chat-list li {
        padding: 10px 15px;
        list-style: none;
        border-radius: 3px
    }
    
    .people-list .chat-list li:hover {
        background: #efefef;
        cursor: pointer
    }
    
    .people-list .chat-list li.active {
        background: #efefef
    }
    
    .people-list .chat-list li .name {
        font-size: 15px
    }
    
    .people-list .chat-list img {
        width: 45px;
        border-radius: 50%
    }
    
    .people-list img {
        float: left;
        border-radius: 50%
    }
    
    .people-list .about {
        float: left;
        padding-left: 8px
    }
    
    .people-list .status {
        color: #999;
        font-size: 13px
    }
    
    .chat .chat-header {
        padding: 15px 20px;
        border-bottom: 2px solid #f4f7f6
    }
    
    .chat .chat-header img {
        float: left;
        border-radius: 40px;
        width: 40px
    }
    
    .chat .chat-header .chat-about {
        float: left;
        padding-left: 10px
    }
    
    .chat .chat-history {
        padding: 20px;
        border-bottom: 2px solid #fff
    }
    
    .chat .chat-history ul {
        padding: 0
    }
    
    .chat .chat-history ul li {
        list-style: none;
        margin-bottom: 30px
    }
    
    .chat .chat-history ul li:last-child {
        margin-bottom: 0px
    }
    
    .chat .chat-history .message-data {
        margin-bottom: 15px
    }
    
    .chat .chat-history .message-data img {
        border-radius: 40px;
        width: 40px
    }
    
    .chat .chat-history .message-data-time {
        color: #434651;
        padding-left: 6px
    }
    
    .chat .chat-history .message {
        color: #444;
        padding: 18px 20px;
        line-height: 26px;
        font-size: 16px;
        border-radius: 7px;
        display: inline-block;
        position: relative
    }
    
    .chat .chat-history .message:after {
        bottom: 100%;
        left: 7%;
        border: solid transparent;
        content: " ";
        height: 0;
        width: 0;
        position: absolute;
        pointer-events: none;
        border-bottom-color: #fff;
        border-width: 10px;
        margin-left: -10px
    }
    
    .chat .chat-history .my-message {
        background: #efefef
    }
    
    .chat .chat-history .my-message:after {
        bottom: 100%;
        left: 30px;
        border: solid transparent;
        content: " ";
        height: 0;
        width: 0;
        position: absolute;
        pointer-events: none;
        border-bottom-color: #efefef;
        border-width: 10px;
        margin-left: -10px
    }
    
    .chat .chat-history .other-message {
        background: #e8f1f3;
        text-align: right
    }
    
    .chat .chat-history .other-message:after {
        border-bottom-color: #e8f1f3;
        left: 93%
    }
    
    .chat .chat-message {
        padding: 20px
    }
    
    .online,
    .offline,
    .me {
        margin-right: 2px;
        font-size: 8px;
        vertical-align: middle
    }
    
    .online {
        color: #86c541
    }
    
    .offline {
        color: #e47297
    }
    
    .me {
        color: #1d8ecd
    }
    
    .float-right {
        float: right
    }
    
    .clearfix:after {
        visibility: hidden;
        display: block;
        font-size: 0;
        content: " ";
        clear: both;
        height: 0
    }
    
    @media only screen and (max-width: 767px) {
        .chat-app .people-list {
            height: 465px;
            width: 100%;
            overflow-x: auto;
            background: #fff;
            left: -400px;
            display: none
        }
        .chat-app .people-list.open {
            left: 0
        }
        .chat-app .chat {
            margin: 0
        }
        .chat-app .chat .chat-header {
            border-radius: 0.55rem 0.55rem 0 0
        }
        .chat-app .chat-history {
            height: 300px;
            overflow-x: auto
        }
    }
    
    @media only screen and (min-width: 768px) and (max-width: 992px) {
        .chat-app .chat-list {
            height: 650px;
            overflow-x: auto
        }
        .chat-app .chat-history {
            height: 600px;
            overflow-x: auto
        }
    }
    
    @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) and (orientation: landscape) and (-webkit-min-device-pixel-ratio: 1) {
        .chat-app .chat-list {
            height: 480px;
            overflow-x: auto
        }
        .chat-app .chat-history {
            height: calc(100vh - 350px);
            overflow-x: auto
        }
    }
</style>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="container">
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card chat-app">
            <div id="plist" class="people-list">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-search"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
                <ul class="list-unstyled chat-list mt-2 mb-0">
                    {%for user in users%}
                        <a href = "{% url 'userauth:chat-page' user.id%}"><li  class="clearfix">
                            <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="avatar">
                            <div class="about">
                                <div class="name">{{user.first_name}} {{user.last_name}}</div>
                                <div class="status"> <i class="fa fa-circle offline"></i> left 7 mins ago </div>                                            
                            </div>
                        </li></a>
                    {%endfor%}
                </ul>
            </div>
            <div class="chat">
                <div class="chat-header clearfix">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
                                <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="avatar">
                            </a>
                            <div class="chat-about">
                                <h6 class="m-b-0">{{user.first_name}} {{user.last_name}}</h6>
                                <small>Last seen: 2 hours ago</small>
                            </div>
                        </div>
                        <div class="col-lg-6 hidden-sm text-right">
                            <a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-info"><i class="fa fa-cogs"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-warning"><i class="fa fa-question"></i></a>
                        </div>
                    </div>
                </div>
                <div class="chat-history"  >
                    <ul class="m-b-0" id="chat-body" style="height: 450px; overflow-y: scroll; overflow-x: hidden;">
                        {%for message in messages%}
                            {%if message.sender == request.user%}
                            <li class="clearfix">
                                <div class="message-data text-right">
                                    <span class="message-data-time">{{message.timestamp}}</span>
                                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">
                                </div>
                                <div class="message other-message float-right"> {{message.message}} </div>
                            </li>
                            {%else%}
                            <li class="clearfix">
                                <div class="message-data">
                                    <span class="message-data-time">{{message.timestamp}}</span>
                                </div>
                                <div class="message my-message">{{message.message}}</div>                                    
                            </li>          
                            {%endif%}                  
                        {%endfor%}
                    </ul>
                </div>
                <div class="chat-message clearfix">
                    <div class="input-group mb-0">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><button id ="chat-message-submit" class="fa fa-send"></button></span>
                        </div>
                        <input id="message_input" type="text" class="form" placeholder="Enter text here...">                                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{{user.id|json_script:"json-username"}}
{{user.username|json_script:"json-username-receiver"}}
{{request.user.username|json_script:"json-message-username"}}

{%endblock body%}
{%block script%}

<script src="{% static 'js/chat.js' %}"></script>
<script>
    $("#chat-body").animate({ scrollTop: 20000000 }, "slow");
</script>
{%endblock script%}

templates/chattest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat App</title>
</head>
<body>
    <input type="text" id="message" placeholder="Nhập tin nhắn">
    <button id="send">Gửi</button>

    <div id="messages"></div>

    <script>
        const messageInput = document.querySelector('#message');
        const sendButton = document.querySelector('#send');
        const messagesContainer = document.querySelector('#messages');

        const channel = new Channel({
            channel_layer: window.channel_layer,
            channel_name: window.channel_name,
        });

        sendButton.addEventListener('click', () => {
            const message = messageInput.value;

            channel.send({
                text: message,
            });

            messageInput.value = '';
        });

        channel.on('message', (data) => {
            const message = data.text;

            messagesContainer.innerHTML += `
                <div class="message">
                    <strong>${data.user.username}</strong>: ${message}
                </div>
            `;
        });
    </script>
</body>
</html>

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/vendor.html
{% extends "index.html" %}
{%load static%}

{%block body%}

<div class="section" id="vendor">
    <div class="container">
        <div class="row">
            <div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-6">
							<div class="header-logo">
								<a href="#" class="logo">

									<img src="{{vendor.image.url}}" alt="" style="width: 100px; height: 100px; color:white">
								</a>
							</div>
                            <div class="row">
                                <div class="col">
                                    <h2 id= "vendorS" href="#" class="logo" style="color: white;">{{vendor.title}}</h2>
                                </div>
                          
                                <div class="col">
                                    <a href="{%url 'userauth:chat-page' vendor.user.id%}" class="primary-btn" style="color: white;">Chat</a>
                                </div>
                                <div class="col">
                                    {%if is_followed%}
                                        <a href="{%url 'userauth:follow' vendor.vid%}" class="primary-btn" style="color: white;">Unfollow</a>
                                    {%else%}
                                        <a href="{%url 'userauth:follow' vendor.vid%}" class="primary-btn"style="color: white;">Follow</a>
                                    {%endif%}
                                </div>
                                
                            </div>
                           
						</div>
						<!-- /LOGO -->
                        <div class="col-md-2">
                            <div class="container">
                                <a id= "vendorS" href="#"  style="color: white;" class="primary-btn">Reviews: {{review_vendor}} <i class="fa fa-star"></i> ({{total_review}}) </a>                           
                                <a id= "vendorS" href="#"  style="color: white;" class="primary-btn"></i>Total sold: {{total_sold}}</a>
                            </div>
                            
    
                        </div>
						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form>
									<input id = "searchVendor" class="input" placeholder="Search here">
									<button class="search-btn">Search</button>
								</form>
							</div>
                            
                            <div id="results-box1" class="cart-list"></div>
						</div>
						<!-- /SEARCH BAR -->

					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
            </div>
        </div>
    </div>
</div>
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <!-- section title -->
            <div class="col-md-12">
                <div class="section-title">
                    <h3 class="title">New Products</h3>
                </div>
            </div>
            <!-- /section title -->

            <!-- Products tab & slick -->
            <div class="col-md-12">
                <div class="row">
                    <div class="products-tabs">
                        <!-- tab -->
                        <div id="tab1" class="tab-pane active">
                            <div class="products-slick" data-nav="#slick-nav-1">
                                <!-- product -->
                                {%for new in new_products%}
                                    <div class="product">
                                        <div class="product-img">
                                            {%if new.image%}
                                                <img src="{{new.image.url}}" alt="">
                                            {%else%}
                                                <img src="{{new.image_url}}" alt="">
                                            {%endif%}
                                        </div>
                                        <div class="product-body">
                                            <p class="product-category">{{new.category.title}}</p>
                                            <h3 class="product-name"><a href="{%url 'product-detail' new.pid%}">{{new.title}}</a></h3>
                                            {%if new.price %}
                                                <h4 class="product-price">{{new.price}} <del class="product-old-price">{{new.old_price}}</del></h4>
                                            {%else%}
                                                <h4 class="product-price">{{new.old_price}}</h4>
                                            {%endif%}
                                            <div class="product-rating">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </div>
                                            <div class="product-btns">
                                                <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                            </div>
                                        </div>
                                        <div class="add-to-cart">
                                            <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                                        </div>
                                    </div>
                                {%endfor%}
                                <!-- /product -->

                            </div>
                            <div id="slick-nav-1" class="products-slick-nav"></div>
                        </div>
                        <!-- /tab -->
                    </div>
                </div>
            </div>
            <!-- Products tab & slick -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->

<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <!-- section title -->
            <div class="col-md-12">
             

                    <!-- STORE -->
                    <div class="col-md-12">
                        <div class="section-title">
                            <h3 class="title">All product</h3>
                        </div>
                    </div>
					<div id="store" class="col-md-12">
                            <!-- store products -->
                            <div id="paginator" class="row">
                                <ul class="store-pagination">
                                    {% if products.has_previous %}
                                        
                                        <li><a href="?page={{ products.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
                                        <li><a href="?page={{ products.previous_page_number }}">{{ products.previous_page_number }}</a></li>
                                    {% endif %}
        
                                    {% if products.number != products.paginator.num_pages  %}
                                        <li class="active"><a href="?page={{ products.number }}">{{ products.number }}</a></li>
                                    {%endif%}
                                        <li> ... {{range}} </li>
                                    {%if products.number == products.paginator.num_pages%}
                                        <li class="active"><a href="?page={{ products.paginator.num_pages }}">{{ products.paginator.num_pages }}</a></li>
                                    {%else%}
                                        <li ><a href="?page={{ products.paginator.num_pages }}">{{ products.paginator.num_pages }}</a></li>
                                    {% endif %}
                                    {% if products.has_next %}
                                        <li><a href="?page={{ products.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                                    {% endif %}
                            
                                </ul></div>
                            <div class="row">
                                {%for product in products%}
                                <!-- product -->
                                <div class="col-md-4 col-xs-8">
                                    <div class="product">
                                        <div class="product-img">
                                            {%if product.image%}
                                                <img src="{{product.image.url}}" alt="">
                                            {%else%}
                                                <img src="{{product.image_url}}" alt="">
                                            {%endif%}
                                            {%if product.price %}
                                                <div class="product-label">
                                                    <span class="sale">-{{product.get_percentage_discount}}%</span>
                                                    <span class="new">NEW</span>
                                                </div>
                                            {%endif%}
                                        </div>
                                        <div class="product-body">
                                            <p class="product-category">{{product.category}}</p>
                                            <h3 class="product-name"><a href="{{product.get_absolute_url}}">{{product.title}}</a></h3>
                                            {%if product.price %}
                                                <h4 class="product-price">{{product.price}} <del class="product-old-price">{{product.old_price}}</del></h4>
                                            {%else%}
                                                <h4 class="product-price">{{product.old_price}}</h4>
                                            {%endif%}
                                            <div class="product-rating">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </div>
                                            <div class="product-btns">
                                                <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                                <button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
                                                <button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
                                            </div>
                                        </div>
                                        <div class="add-to-cart">
                                            <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                                        </div>
                                    </div>
                                </div>
                            {%endfor%}
							<!-- /product -->
						</div>
                        
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
            <!-- /section title -->

{%endblock body%}
{%block script%}
<script>
    const results = document.querySelector("#vendorS");
    $(document).ready(function() {
        // Thêm sự kiện lắng nghe thay đổi cho trường tìm kiếm
        $("#searchVendor").on("keyup", function() {
            // Gửi yêu cầu AJAX
            $.ajax({
                url: "/searchVendor",
                type: "GET",
                data: {
                    q: $(this).val(),
                    vendor : results.textContent,
                },
                success: function(response) {
                    // Cập nhật danh sách sản phẩm
                    $("#results-box1").html(response.results.map(function(product) {
                        return `
                        <div class="product-widget">
                            <div class="product-img" >
                                <img src="${product.image}" alt="">
                            </div>
                            <div class="product-body">
                                <h3 class="product-name"><a href="${product.url}">${product.title}</a></h3>
                                <h4 class="product-price"><span class="qty">1x</span>${product.price}</h4>
                            </div>
                        </div>
                        `;
                    }));
                }
            });
        });
    });
</script>
{%endblock script%}