Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path("",include("core.urls")),
    path("accounts/",include("userauth.urls")),
    path('accounts/', include('allauth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_ENABLED is True:
    urlpatterns += [path('admin/', admin.site.urls),]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

core/urls.py
from django.urls import path,include
from .views import index,StoreView,ProductView,VendorView,CategoryView,CartView,CheckoutView,OrderDetailView,PayMentCompletedView,WishListView
from .function import search,search_vendor,filter_product,check_product,add_to_cart,delete_from_cart,update_from_cart,order_create,add_review,delete_order,add_to_wishlist,remove_from_wishlist
urlpatterns = [
    path("",index,name="index"),

    path("store/",StoreView,name="store"),
    path("filter-product/",filter_product,name="filter-product"),

    path("product/<pid>/",ProductView,name="product-detail"),
    path("check-product/",check_product,name="check-product"),
    path("add-to-cart/",add_to_cart,name="add-to-cart"),
    path("add-review/",add_review,name="add-review"),

    path("shop/<vid>/",VendorView,name="vendor-detail"),
    path("category/<cid>",CategoryView,name="category-detail"),


    path("cart/",CartView,name="cart-detail"),
    path("<pid>/delete-from-cart/",delete_from_cart,name="delete"),
    path("update-from-cart/",update_from_cart,name="update"),

    path("search/",search,name="search"),
    path("searchVendor/",search_vendor,name="searchVendor"),

    path("checkout/",CheckoutView,name="checkout"),
    path("order/",order_create,name="order"),
    path("order-detail/<invoice>",OrderDetailView,name="order-detail"),
    path("delete-order/<invoice>",delete_order,name="delete-order"),
    path("paypal/",include("paypal.standard.ipn.urls")),
    path("payment-completed/",PayMentCompletedView,name="payment-completed"),

    path("wishlist",WishListView,name="wishlist"),
    path("add-to-wishlist/",add_to_wishlist,name="add-to-wishlist"),
    path("remove-from-wishlist/<pid>",remove_from_wishlist,name="remove-from-wishlist")
]

userauth/urls.py
from django.urls import path
from .views import register_view,login_view,logout_view,follow,profile_view,edit_profile,MessageView
from chat.views import index,chatPage
app_name = "userauth"
urlpatterns = [
    path("register/",register_view,name="register"),
    path("login/",login_view,name="login"),
    path("logout/",logout_view,name="logout"),
    path("follow/<vid>/",follow,name="follow"),
    path("",profile_view,name="profile"),
    path("profile/",edit_profile,name="profile-update"),
    path("inbox/",index,name="chat"),
    path("chat-user/<uid>/",chatPage,name="chat-page"),

]

userauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.import datetime
from django.core.cache import cache
import datetime

def user_directory_path(instance,filename):
    return 'user_{0}/{1}'.format(instance.id,filename)
class User(AbstractUser):
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to=user_directory_path,null=True,default="none.jpg")
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self) :
        return self.email

class Follow(models.Model):
    follower = models.ForeignKey(User,on_delete=models.CASCADE,related_name="follower")
    following = models.ForeignKey(User,on_delete=models.CASCADE,related_name="following")

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauth.models import User
from core.models import Address
from urllib import request

def user_directory_path(instance,filename):
    return 'user_{0}/{1}'.format(instance.id,filename)
class UserRegisterForm(UserCreationForm):
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'input','placeholder':'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    class Meta:
        model = User
        fields = ['username','email'] 
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={ 'placeholder': 'Password from numbers and letters of the Latin alphabet'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={ 'placeholder': 'Password confirmation'})

class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'input'}))
    last_name = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'input','placeholder': 'Last name'}))
    image = forms.ImageField()
    class Meta:
        model = User
        fields = ['first_name','last_name','image'] 

class AddressEditForm(forms.ModelForm):
    address = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'input','placeholder': 'Address'}))
    phone = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'input','placeholder': 'Phone number'}))
   # location = forms.PointField(required=False)
    class Meta:
        model = Address
        fields = ['address','phone'] 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].widget.attrs['placeholder'] = self.fields['address'].label or 'Address'
        self.fields['phone'].widget.attrs['placeholder'] = self.fields['phone'].label or 'Address'

userauth/views.py
from django.shortcuts import render,redirect,get_object_or_404
from userauth.forms import UserRegisterForm,UserProfileForm,AddressEditForm
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from django.conf import settings
from core.models import Vendor,Product,Order,OrderItems,Address
from .models import Follow,User
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

def handle_not_found(request, exception):
    return render(request, "404.html")


# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return redirect("index")
    if request.method=="POST":
        email = request.POST.get('your_name')
        password = request.POST.get('your_pass')
        try:
            user= User.objects.get(email=email)
        except:
            print("not exist")
            messages.warning(request,f"User with {email} does not exist")
        user = authenticate(request,email=email,password=password)
        if user is not None:
            print("Exist")
            login(request,user)
            messages.success(request,"You are logged in.")   
            return redirect("index")
        else:
            return render(request,'userauth/log-in.html')
    else:
        return render(request,'userauth/log-in.html')
    
@csrf_exempt
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password1")
            repass = form.cleaned_data.get("password2")
            if password == repass:
                new_user = authenticate(username=username,email=email,password=password)
                login(request, new_user)
                messages.success(request, f'Your account was created!!')
                return redirect('index')
        
    else:
        form = UserRegisterForm()
    context = {
        'form': form
    }
    return render(request,"userauth/sign-up.html",context)
@login_required
def logout_view(request):   
    logout(request)
    return redirect('userauth:login')
@login_required
def follow(request,vid):
    user = request.user
    vendor = get_object_or_404(Vendor,vid=vid)
    try: 
        follow = Follow.objects.get(follower=user,following=vendor.user)
        follow.delete()
    except:
        follow = Follow.objects.create(follower=user,following=vendor.user)
        
    return redirect('vendor-detail',vendor.vid)
@login_required
def profile_view(request):

    products = {}
    try:
        order = Order.objects.filter(user=request.user).all()
        
    except:
        order = {}
        item = {}
    user = User.objects.get(id = request.user.id)
    address = Address.objects.filter(user=user).first()
    context = {
       
        'products' : products,
        'orders': order,
        'user': user,
        'address': address if address else {}
    }
    return render(request,"userauth/profile.html",context)
@login_required
def edit_profile(request):
    profile = User.objects.get(id=request.user.id)
    print(profile.first_name,profile.last_name,profile.image)
    address_user = Address.objects.filter(user = request.user).first()
    if request.method == "POST":
        first_name = request.POST.get("first-name")
        last_name = request.POST.get("last-name")
        address= request.POST.get("address")
        phone= request.POST.get("tel")
        image = request.FILES.get('imageUp')
        print(request.FILES.get('imageUp'))
        profile.first_name = first_name
        profile.last_name= last_name
        profile.image = image if image else profile.image
        profile.save()
        address_user.address= address
        address_user.phone = phone
        address_user.save()
        orders = Order.objects.filter(user=request.user).all()
        
        context = {
            'user' : request.user,
            'orders': orders,
            'address': address_user
            
        }
        return render(request,"userauth/profile.html",context)
    if not address_user:
        address_user = Address.objects.create(user=request.user,address="",phone=0)
    context = {
        'profile':profile,
        'address': address_user,
    }
    return render(request,"userauth/profile-update.html",context)

def update_product_vendor(request):
    pass
def register_vendor(request):
    pass

def MessageView(request):
    return render(request,"chat.html")

templates/userauth/log-in.html
{% extends "userauth/sign-up.html" %}
{%load static%}
{% load socialaccount %}

{%block content%}

<section class="sign-in">
  <div class="container">
      <div class="signin-content">
          <div class="signin-image">
              <figure><img src="{%static 'img/signin-image.jpg' %}" alt="sing up image"></figure>
              <a href="{%url 'userauth:register'%}" class="signup-image-link">Create an account</a>
          </div>

          <div class="signin-form">
              <h2 class="form-title">Login</h2>
              <p> (Account demo)  </p>
                <p>Email: demo@gmail.com</p>
                <p>Password: Demo123456. </p>
              <form method="POST" class="register-form">{% csrf_token %}
                  <div class="form-group">
                      <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                      <input type="text" name="your_name" id="your_name" placeholder="Your Name"/>
                  </div>
                  <div class="form-group">
                      <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                      <input type="password" name="your_pass" id="your_pass" placeholder="Password"/>
                  </div>
                  <div class="form-group">
                      <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                      <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                  </div>
                  <div class="form-group form-button">
                      <button type="submit" name="signin" id="signin" class="form-submit">Log in</button>
                  </div>
              </form>
              <div class="social-login">
                  <span class="social-label">Or login with</span>
                  <ul class="socials">
                      <li><a href="{% provider_login_url 'google' %}"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                  </ul>
              </div>
          </div>
      </div>
  </div>
</section>

{%endblock content%}

templates/userauth/profile-update.html
{%extends "index.html"%}
{%block nav%}
{%endblock nav%}
{%block body%}
<div class="container bootstrap snippets bootdey">
    <h1 class="text-primary">Edit Profile</h1>
      <hr>
	<div class="row">
      <!-- left column -->
   
        <form method="POST" class="form-horizontal" role="form" enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="col-md-3">
              <div class="text-center">
                  {%if profile.image%}
                    <img height="300" width="300" src={{profile.image.url}}>
                  {%endif%}
                  <input type="file" name="imageUp" accept="image/*">
                <h6>Upload a different photo...</h6>
          
              </div>
            </div>
            
            <!-- edit form column -->
            <div class="col-md-9 personal-info">
              {%if user_form.errors%}
              <div class="alert alert-info alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                <i class="fa fa-coffee"></i>
               {{user_form.errors}}
              </div>
              {%endif%}
              <h3>Personal info</h3>
              
          <div class="form-group">
            <label class="col-lg-3 control-label">First name:</label>
            <div class="col-lg-8">
              <input class="input" type="text" name="first-name" placeholder="{{request.user.first_name}}" value="{{request.user.first_name}}">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label">Last name:</label>
            <div class="col-lg-8">
              <input class="input" type="text" name="last-name" placeholder="{{request.user.last_name}}"  value="{{request.user.last_name}}">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label">Address:</label>
            <div class="col-lg-8">
              <input class="input" type="text" name="address" placeholder="{{address.address}}"  value="{{address.address}}">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label">Phone number:</label>
            <div class="col-lg-8">
              <input class="input" type="tel" name="tel" placeholder="{{address.phone}}"  value="{{address.phone}}">
            </div>
          </div>
          <button type="submit" class="btn btn-primary center-block">Update</button>
        </form>
      </div>
  </div>
</div>
<hr>
{%endblock body%}

templates/userauth/profile.html
{%extends "index.html"%}
{%load static%}
{%block nav%}
{%endblock nav%}
{%block body%}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="user-profile__avatar shadow-effect text-center">
        
        {%if user.image%}
          <img width="200" height="200" class="img-responsive center-block" src="{{user.image.url}}" alt>
        {%else%}
          <img width="200" height="200" class="img-responsive center-block" src="{{user.image}}" alt>
        {%endif%}
        {{user.first_name}} {{user.last_name}}
  
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          User Menu
        </div>
        <div class="panel-body">
          <ul>
            <li><a href="#"><i class="fa fa-user"></i> My Profile</a></li>
            <li><a href="{%url 'userauth:profile-update'%}"><i class="fa fa-edit"></i> Edit Profile</a></li>
            <li><a href="{%url 'userauth:chat'%}"><i class="fa fa-envelope-o"></i> Messages</a></li>
            <li><a href="{%url 'userauth:logout' %}"><i class="fa fa-sign-out"></i> Sign Out</a></li>
          </ul>
        </div>
      </div>

    </div>
    <div class="col-sm-9">
      <div class="row">
        <div class="col-sm-6">
          
          <!-- User name -->
          <h3 class="user-profile__title">{{user.first_name}} {{user.last_name}}</h3>
          
          <!-- User description -->
          <p class="user-profile__desc">
            Address: {{address.address}}
          </p>
          <p class="user-profile__desc">
            Phone number: {{address.phone}}
          </p>
          <!-- User URL -->
          <!-- User social links -->
          <div class="social">
            <ul class="list-inline">
              <li>
                <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              </li>
              <li>
                <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              </li>
              <li>
                <a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          
          <!-- Profile info -->
          <ul class="user-profile__info">
            
          </ul>
        </div>
        <div class="col-sm-12">
          <div class="user-profile__tabs">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
          
              <li role="presentation" class="">
                <a href="#user-profile__shopping-cart" aria-controls="user-profile__shopping-cart" role="tab" data-toggle="tab" aria-expanded="true">My Order</a>
              </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane fade" id="user-profile__shopping-cart">
                <div class="table-responsive">
                  <table class="table table-bordered shopping-cart__table">
                  <thead>
                    <tr>
                      <th>Preview</th>
                      <th>Invoice</th>
                      <th>Address</th>
                      <th>Price</th>
                      <th>Status</th>
                      <th>Details</th>
                    </tr>
                  </thead>
                  <tbody>
                    {%for order in orders%}
                      <tr class="js-shop__item">
                        <td>
                          {%if order.image%}
                            <img width="50" height="50"class="img-responsive shopping-cart-item__img" src="{{order.image.url}}" alt="...">
                          {%endif%}
                        </td>
                        <td>
                          <div class="shopping-cart-item__title">
                            {{order.invoice_no}}
                          </div>
                        <td>
                          <div class="shopping-cart-item__title">
                            {{address.address}}
                          </div>
                        </td>
                        <td><span class="js-shop-item__price">{{order.price}}</span></td>
                        <td> {{order.product_status}}</td>
                        <td><a href="{%url 'order-detail' order.invoice_no%}" class="text-success" >View</a>
                        
                      </tr>
                    {%endfor%}
                  </tbody>
                  </table>
            </div> <!-- / .tab-content -->
          </div>
        </div>
      </div> <!-- / .row -->
    </div>
  </div> <!-- / .row -->

<!-- 
{%if is_vendor%}
    <div class="row">
        <div class="col-md-12">
            <div class="section-title">
                <h3 class="title">All product</h3>
            </div>
        </div>
        <div id="store" class="col-md-9">
               
            {%for product in products%}
                <div class="row">
                    
                    <div class="col-md-4 col-xs-6">
                        <div class="product">
                            <div class="product-img">
                              {%if product.image%}
                                <img src="{{product.image.url}}" alt="">
                              {%else%}
                                <img src="{{product.image_url}}" alt="">
                              {%endif%}
                                <div class="product-label">
                                    <span class="sale">-30%</span>
                                    <span class="new">NEW</span>
                                </div>
                            </div>
                            <div class="product-body">
                                <p class="product-category">{{product.category}}</p>
                                <h3 class="product-name"><a href="{{product.get_absolute_url}}">{{product.title}}</a></h3>
                                <h4 class="product-price">{{product.price}}<del class="product-old-price">{{product.old_price}}</del></h4>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                                <div class="product-btns">
                                    <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                    <button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
                                    <button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
                                </div>
                            </div>
                            <div class="add-to-cart">
                                <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                            </div>
                        </div>
                    </div>
                {%endfor%}
                
            </div>
        </div>
    </div>  
{%endif%}
/ .vendor -->
</div>
{%endblock body%}

templates/userauth/sign-up.html
{%load static%}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{%static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Main css -->
    <link rel="stylesheet" href="{%static 'css1/style.css' %}">
</head>
<body>

    <div class="main">
       
        <!-- Sign up form -->
        {% block content%}
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    
                    <div class="signup-form">
                        
                        <h2 class="form-title">Sign up</h2>
                        {%if form.errors %}
                            <div class=alert alert-danger">
                                <strong>Error</strong>
                            </div>
                        {%endif%}
                        <form method="POST" class="register-form" >
                            {% csrf_token %}
                            {% if form.non_field_errors %}
                                {% for error in form.non_field_errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                    
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                    
                            {% for field in form %}
                                {{ field }}
                                {{ field.errors.as_ul }}
                            {% endfor %}
                     
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{%static 'img/signup-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{%url 'userauth:login'%}" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>
        {% endblock content%}
        <!-- Sing in  Form -->
       
</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{%static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{%static 'js/main.js' %}"></script>
</html>